### ISSUE TITLE
About the purpose of Webflux

### ISSUE THREAD

**Issue by HelloTo4x** [peavers/jackett-rss-processor#871]
Hi, i am reading your project, can u tell me the purpose of Webflux, reactive in your project ? Is it for increasing performance, can u tell me some disadvantaged of Webflux ?

**Comment by peavers** [comment]
Hi, that's a very open and opinionated question. If you're wanting to know why someone would choose to write code in more of a functional and reactive paradigm then you can refer to this great article: https://medium.com/@shaistha24/functional-programming-vs-object-oriented-programming-oop-which-is-better-82172e53a526

If you'd like to know more about the pros and cons specifically of using webflux in SpringBoot https://medium.com/intuit-engineering/reactive-programming-project-reactor-webflux-oh-my-4bfa470feee7#:~:text=WebFlux%20allows%20for%20more%20scalability,WebFlux%20model%20for%20another%20controller.

And finally if you'd like to know why I decided to use webflux for this project instead of the more traditional paradigms then it is simply because webflux is a nicer and more fun way of writing code 👍

**Comment by HelloTo4x** [comment]
thank u so much
